config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :tweets, except: [:new]
  root 'tweets#index'
  
  
  

end

app/models/tweet.rb
# == Schema Information
#
# Table name: tweets
#
#  id         :integer          not null, primary key
#  content    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tweet < ActiveRecord::Base

  belongs_to :user

  validates :content,
  presence: { message: "文字を入力してください" },
  length: { maximum: 140, message: "140字以内で入力して下さい" }

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string
#  account                :string
#  icon                   :string
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :tweets

  validates :name, presence: true, uniqueness: true
  validates :account, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) << :name
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
    devise_parameter_sanitizer.for(:sign_in) << :account
    devise_parameter_sanitizer.for(:sign_up) << :account
    devise_parameter_sanitizer.for(:account_update) << :account
    devise_parameter_sanitizer.for(:sign_in) << :icon
    devise_parameter_sanitizer.for(:sign_up) << :icon
    devise_parameter_sanitizer.for(:account_update) << :icon

  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  def index
    if signed_in?
      @tweets = Tweet.all
      @tweet = Tweet.new
      @user = current_user#User.where(id: current_user.id).last
      @others = User.where('id != ?', current_user.id) #where('id NOT IN ?' , [配列])とする事で、当てはまらないものを選択
    else
      redirect_to new_user_registration_path
    end

  end
  
  def new
    @tweet = Tweet.new
  end
  
  def create
	  @tweet = Tweet.new(tweet_params)
    @tweets = Tweet.all
    @user = current_user #User.where(id: current_user.id).last
	  @tweet.save
    render 'index'

  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    @tweets = Tweet.all
    @user = current_user
    render 'index'
  end

  private
    
    def tweet_params
      params.require(:tweet).permit(:content).merge(user_id: current_user.id)

    end
	
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twotter</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    "bootstrap", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <nav>
    <%= link_to (image_tag "home.png",:id => "homeicon"), tweets_path %>
    <%= image_tag("logo.png", :id => "headerlogo") %>
    <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->

    <container id = "headernavi">
    <% if user_signed_in? %>
        <!-- current_user は現在ログインしているUserオブジェクトを返すdeviseのHelperメソッド -->
        <!-- *_path はUserモデルを作成したときに、
          deviseにより自動で作成されてますので、rake routesで確認できます -->
        <%= link_to 'ユーザ情報の変更', edit_user_registration_path %> |
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <% else %>
        <%= link_to "アカウント作成", new_user_registration_path %> |
        <%= link_to "ログイン", new_user_session_path %>
    <% end %>
    </container>

    <%= image_tag("tweet.png", :id => "tweeticon") %>

  </nav>
</header>

<p class="notice"><%= notice %></p>

<p class="alert"><%= alert %></p>



<%= yield %>

app/views/tweets/_tweets.html.erb
<dev class = "tweetshown">
<% @tweets.reverse_order.each do |tweet| %>
    <hr>
    <% if tweet.user.icon.present? %>
        <%= image_tag tweet.user.icon, width: 40, height: 40, :class => "img-rounded" %>
    <% else %>
        <%= image_tag 'http://ks.c.yimg.jp/res/chie-0/309/267/i1/img.PNG', width: 40, height: 40, :class => "img-rounded" %>
    <% end %>

    <%= tweet.user.name %>@<%= tweet.user.account %>・<%= tweet.created_at.in_time_zone("Asia/Tokyo").strftime("%Y/%m/%d %H:%M:%S") %>

    <% if signed_in? && current_user == tweet.user %>
        <%= link_to (image_tag "dustbox.png", width: 20, height: 20), tweet, method: :delete, data: {confirm: 'ツイートを削除します。'}, remote: true %>
    <% end %>
    <br/>
    <%= tweet.content %>

    <br/><br/>
<% end %>
</dev>

app/views/tweets/index.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-4 column" , id="userprofile">

      <% if current_user.present? %>

          <% if current_user.icon.present? %>
              <%= image_tag current_user.icon, :class => "profileicon" %>

          <% else %>
              <%= image_tag 'http://ks.c.yimg.jp/res/chie-0/309/267/i1/img.PNG', :class => "profileicon" %>

          <% end %>

          <p class="profilename"><%= current_user.name %><br/></p>

          <p class="profileaccount"><%= "@" + current_user.account %></p>

          <div class="row clearfix">
            <div class="col-md-4 column">

              <p>ツイート</p>

              <div id="tweetcount"><%= @user.tweets.count %></div>

            </div>
            <div class="col-md-4 column">

              <p>フォロー</p>

              <p>未実装</p>

            </div>
            <div class="col-md-4 column">

              <p>フォロワー</p>

              <p>未実装</p>

            </div>
          </div>

      <% end %>
    </div>


    <div class="col-md-6 column">
      <div class="tweetcolumn">

        <div id="tweetarea">
          <% if signed_in? %>
              <%= form_for(@tweet, remote: true) do |f| %>

                  <% if @tweet.errors.any? %>
                      <%= @tweet.errors.messages[:content][0] %>

                  <% end %>

                  <br>

                  <p id="howru">いまどうしてる？</p>
                  <%= f.text_area :content, :id => "textarea" %>
                  <span id="lettercount">140</span>
                  <%= f.submit 'ツイート', :id => "tweetbutton" %>
                  <br/>
              <% end %>
          <% end %>
        </div>


        <div id="tweets">
          <%= render :partial => "tweets" %>
        </div>
      </div>

    </div>
    <div class="col-md-2 column">
      <dev id="otherscolumn">

        <h4>他のユーザー</h4>

        <% if @others.present? %>
            <% @others.each do |other| %>
                <% if other.icon.present? %>
                    <%= image_tag other.icon, width: 40, height: 40, :class => "img-rounded" %>
                <% else %>
                    <%= image_tag 'http://ks.c.yimg.jp/res/chie-0/309/267/i1/img.PNG', width: 40, height: 40, :class => "img-rounded" %>
                <% end %>

                <%= other.name %>
                @<%= other.account %>
                <br/><br/>
            <% end %>
        <% end %>

      </dev>
    </div>
  </div>
</div>

app/views/tweets/index.js.erb
jQuery(function ($) {
    $('#tweets').html("<%= j(render('tweets')) %>");
    $('#tweetcount').html("<%= @user.tweets.count %>");
});